# Description: Config file for sLSTM-only model
training:
  batch_size: 64
  lr: 1e-5
  seed: 42
  num_epochs: 100
  lr_warmup_steps: 3000
  lr_decay_until_steps: 30000
  lr_decay_factor: 0.001
  weight_decay: 0.0001
  device: cuda
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  save_checkpoint: "test_2048_3108"
  load_checkpoint: null
  test_every_epoch: 1
  log_every_step: 3_000
  clearml_task_name: "test_2048_3108_0"

model:
  num_blocks: 2
  embedding_dim: 2048
  mlstm_block:
    mlstm:
      num_heads: 1
  slstm_block: {}
  slstm_at: []
  context_length: ${dataset.kwargs.context_length}
  vocab_size: ${dataset.kwargs.vocab_size}

tokenizer: VietAI/envit5-base

dataset:
  name: hiimbach/envi_translation
  proportion: 0.1
  kwargs:
    vocab_size: 50101
    enable_mask: true
    context_length: 256
    min_sequence_length: 1
    max_sequence_length: 40
